<template>
  <div>
    <PageTitle>Terms</PageTitle>

    <p>Stratis Group Europe, a Spanish company (&ldquo;Stratis,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), currently provides a method of access to, and certain information about, Verium network, a layer-2 protocol that scales Stratis (&ldquo;Verium&rdquo;) as well as related content and functionality about Verium through websites located at https://verium.stratisplatform.com, https://zkstratis.explorer.stratisplatform.com/, https://zkauroria.explorer.stratisplatform.com (each, a &ldquo;Site&rdquo; and collectively, the &ldquo;Sites&rdquo;). We also currently provide access and information about Verium through our related technologies, including all of our existing and any updated or new features, functionalities and technologies (collectively, the &ldquo;Service&rdquo;).</p>
    <p>These Website Terms and Conditions (these &ldquo;Terms&rdquo;) set forth the legally binding terms and conditions that govern your use of the Sites. Please note that certain parts and features of the Site may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such parts and features. All such additional terms, guidelines, and rules, including but not limited to the Privacy Policy, and the Cookies Policy, are incorporated by reference into these Terms. By accessing or using the Site, you are accepting these Terms (on behalf of yourself or the entity that you represent), and you represent and warrant that you have the willingness, right, authority, and capacity to enter into these Terms (on behalf of yourself or the entity that you represent).</p>
    <p>SECTION 10 CONTAINS AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN YOU AND US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION.&nbsp;<strong>UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT (A) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST STRATIS GROUP EUROPE ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, AND (B) YOU ARE AGREEING TO MANDATORY INDIVIDUAL ARBITRATION FOR THE RESOLUTION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL ON YOUR CLAIMS</strong>. PLEASE NOTE THAT YOUR USE OF THE SITES IS SUBJECT TO THESE TERMS. IF YOU DO NOT AGREE TO ALL OF THESE TERMS IN THEIR ENTIRETY, YOU MAY NOT USE ANY SITE IN ANY MANNER.</p>
    <p><strong>DISCLAIMER</strong></p>
    <ul>
    <li>EACH SITE IS PROVIDED BY STRATIS GROUP EUROPE ON AN &ldquo;AS-IS&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT AVAILABILITY, ACCESSIBILITY, OR USE OF THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE.</li>
    <li>We make no representation, warranty, guarantee, or undertaking regarding ZKsync or any of its products, services, or activities, whether express or implied, including but not limited to warranties of compliance, accuracy, reliability, validity, merchantability, fitness for a particular purpose, quality, availability, durability, and noninfringement, or as to any of it being uninterrupted, error free, free of harmful components, or secure.</li>
    <li>We are not liable for, or in connection with, any actions, proceedings, claims, damages, expenses or other liabilities, whether in an action of contract, tort or otherwise, arising from, related to or in connection with ZKsync or any of its products, services, or activities, or the use or dealings in or with any of them or in reliance thereon.</li>
    <li><strong>We are not, do not speak for, and cannot bind, the ZKsync community.</strong>&nbsp;The ZKsync community is a collection of independent contributors to ZKsync. Stratis Group Europe is a separate, independent entity.</li>
    <li><strong>We do not endorse third parties or third party information</strong>. Any time we link to, quote or otherwise reference a third party or reproduce or incorporate their information, content or material, it is solely for informational purposes. You should not assume that we have verified the accuracy of, or endorse in any way, such information, content or materials.</li>
    <li>When we talk about future ideas or prospects, we are expressing our vision and hopes, and there is no commitment or guarantee that it will come true, that we will implement any of it, or that it will work.</li>
    </ul>
    <ol>
    <li><strong>Access to the Sites</strong>. You may only access or use the Site or accept the Terms if you are an individual of legal age to form a binding contract (or if not, you have received your parent&rsquo;s or guardian&rsquo;s permission to use the Site and have gotten your parent or guardian to agree to the Terms on your behalf). If you are agreeing to the Terms on behalf of an organization or entity, you represent and warrant that you are authorized to agree to the Terms on that organization&rsquo;s or entity&rsquo;s behalf and bind them to the Terms (in which case, the references to &ldquo;you&rdquo; and &ldquo;your&rdquo; in the Terms, except for in this sentence and in the paragraph directly above, refer to that organization or entity).</li>
    <li><strong>License</strong>. Subject to these Terms, you are hereby granted a non-transferable, non-exclusive, revocable, limited license to use and access the Site and the Services solely for your own personal, non-commercial use, subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, whether in whole or in part, or any content displayed on the Sites; and (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Sites. All copyright and other proprietary notices on the Sites (or on any content displayed on the Sites) must be retained on all copies thereof.</li>
    <li><strong>Changes to the Terms</strong>. We reserve the right to change the Terms at any time. All changes are effective immediately when we post them. Your continued use of the Site following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.</li>
    <li><strong>Intellectual Property Rights</strong>. The Sites and their entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection, and arrangement thereof), are owned by us, our licensors or other providers of such material and are protected by copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. Neither these Terms (nor your access to the Sites) transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except as indicated otherwise.</li>
    <li><strong>Feedback</strong>. If you provide us with any feedback or suggestions regarding the Sites (<strong>&ldquo;Feedback&rdquo;</strong>), you hereby assign to us all rights in such Feedback and agree that we have the right to use and fully exploit such Feedback and related information in any manner we deem appropriate. Any Feedback you provide will be treated as non-confidential and non-proprietary, and we will be entitled to the unrestricted use and dissemination of such Feedback for any purpose, commercial or otherwise, without acknowledgment, attribution, or compensation to you.</li>
    <li><strong>Third-Party Materials</strong>. The Sites contain references, links, and enables you to connect to third-party resources including (but not limited to) Web3 wallets, non-standard bridges, applications, and other information, materials, products, or services, which we do not own or control (collectively, &ldquo;third-party products&rdquo;). We do not approve, monitor, endorse, make any representations or warranties (expressly or implicitly) or assume any responsibility for any third-party products, any component thereof, or the manner in which those products or components interact with the Sites. When you use or rely on any third-party products, you do so at your own risk. You understand that you are solely responsible for any fees or costs associated with using third-party products and that, unless stated herein, the Terms do not otherwise apply to your dealings or relationships with any third parties or third-party products.</li>
    <li><strong>Prohibited Uses</strong>. You may use the Sites only for lawful purposes and in accordance with these Terms. You agree&nbsp;<strong>not</strong>&nbsp;to use the Sites:</li>
    </ol>
    <ul>
    <li>in any way that violates any applicable federal, state, local, or international law or regulation, including, without limitation, any applicable sanctions laws, export control laws, securities laws, anti-money laundering laws, privacy laws;</li>
    <li>use any device, software or routine that interferes with the proper working of any Site;</li>
    <li>attempt to probe, scan or test the vulnerability of Verium, or otherwise seek to interfere with or compromise the integrity, security, or proper functioning of Verium;</li>
    <li>attempt to interfere with the proper working of the Sites, or interfere with, damage, or disrupt any parts of the Sites, the server(s) on which the Sites is stored, or any server, computer or database connected to the Sites;</li>
    <li>further or promote any criminal activity or enterprise or provide instructional information about illegal activities; or</li>
    <li>encourage or enable any other individual to do any of the foregoing.</li>
    </ul>
    <ul>
      <li><strong>Indemnification</strong>. To the fullest extent permitted by applicable laws, you agree to indemnify, defend and hold harmless Stratis Group Europe, as well as its affiliates and service providers, and each of their respective past, present and future officers, directors, members, employees, consultants, representatives and agents, and each of their respective successors and assigns (the &ldquo;Indemnified Parties&rdquo;) from and against all actual or alleged third party claims, damages, awards, judgments, losses, liabilities, obligations, taxes, penalties, interest, fees, expenses (including, without limitation, attorneys&rsquo; fees and expenses) and costs (including, without limitation, court costs, costs of settlement and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract or otherwise (collectively, &ldquo;Claims&rdquo;), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to: (a) your use of the Site; (b) your violation of these Terms or applicable law; (c) your violation of the rights of a third party; and (d) your negligence or willful misconduct. You agree to promptly notify us of any third party Claims and cooperate with the Indemnified Parties in defending such Claims. You further agree that the Indemnified Parties shall have the right to control the defense or settlement of any third party Claims as they relate to us, if it so chooses.</li>
      <li><strong>Limitation of Liability</strong>. TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL THE INDEMNIFIED PARTIES OR ANY OF THEM BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR: (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION; (B) ANY SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY; (C) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF ONE-HUNDRED ($100) DOLLARS; OR (D) ANY MATTER BEYOND THE REASONABLE CONTROL OF THE INDEMNIFIED PARTIES OR ANY OF THEM. SOME JURISDICTIONS...</li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
</script>

<style lang="scss" scoped>
  p {
    margin-block-start: 1em;
    margin-block-end: 1em;
  }
  ul {
    list-style: initial;
  }
  ol {
    list-style: decimal;
  }
  li {
    padding-bottom: 1em;
  }
</style>